### ISSUE TITLE
[Feature Request] oEmbed for Frontend based playgrounds and videos

### ISSUE THREAD

**Issue by IamManchanda** [TechDotIO/techio-documentation#10]
For front based articles 
Runnable is not needed but codepen.

Example:
https://codepen.io/IamManchanda/full/eWKPqE/
https://www.youtube.com/watch?v=FKzzaWR6j2M

What oEmbed look to do is this:
1. You add a URL 
2. You press space and enter
3. oEmbed will fetch and put the embedded URL in it 

Site using them => Medium, Scotch.io and many others

**Comment by sidsharma27** [comment]
Hi @IamManchanda :) 

We do actually have that for youtube videos, but not for CodePen. I'll relay your feedback to the product team.  By the way, you can also add [viewers](https://tech.io/playgrounds/408/tech-io-documentation/add-a-viewer) for front end though so it's not necessary to use CodePen.

**Comment by IamManchanda** [comment]
> A viewer is a HTTP service that renders content from the runner to an <iframe> inside the playground page. You can create your own HTTP server from your code or use a simplified server given by Tech.io.

@sidsharma27 Where can I get a simplified server from tech.io?

Secondly Codepen is popular for frontend embeding so better would be codepen!

**Comment by IamManchanda** [comment]
BTW Codepen has a debug mode too 
https://s.codepen.io/IamManchanda/debug/eWKPqE/ZoMBajmdNEWk

so yes I can use their server for iframe too! 
But still having Codepen embedding would be useful for community!

**Comment by sidsharma27** [comment]
Will let the product team know and will update you accordingly :) Thanks for brining it to our attention!

**Comment by IamManchanda** [comment]
Adding links based on talk with Thibaud Jobert

https://blog.codepen.io/documentation/features/embedded-pens/
https://codepen.io/IamManchanda/embed/GMWoWB/

**Comment by 2StepsFr0mHell** [comment]
We've added oEmbed, but we are using a whitelist. For now, we don't want to support Codepen embeds in Tech.io playgrounds.
