### ISSUE TITLE
[Build/Bug] Inline formula inside markdown table makes build crash

### ISSUE THREAD

**Issue by loicmarie** [TechDotIO/techio-documentation#13]
It seems like putting an inline latek formula inside a markdown table makes playground crash at build step.

**To reproduce:**

Create playground and put the following lines in a .md file:
```
| test1 | test2 |
|-------|-------|
| key1 | val1 |
| key2 | $`a = b`$ |
```
**Logs at build step**
```
# Get the source from the git repository
# Read the techio.yml file
# Build project python
No need to build project python as it has not been modified

Internal error
```

I don't think it's important to handle inline latek inside tables, but maybe the error should be more explicit

**Comment by FredTreg** [comment]
Hello,

You are correct. We have filed a bug. We'll let you know when this is fixed

**Comment by CGNonofr** [comment]
Hello,

It should be fixed now!

**Comment by loicmarie** [comment]
I confirm, thank you !
