### ISSUE TITLE
[Feature Request] Right to left text support

### ISSUE THREAD

**Issue by bary12** [TechDotIO/techio-documentation#15]
I'm not sure if this is the right repository, but I didn't find a proper issue tracker for tech.io so I'm gonna ask here (Is the project itself open source?)

I'm teaching middle school students in Israel which are not all proficient in English. So I want to create a playground in Hebrew but the text is aligned to the left.

![screenshot_52](https://user-images.githubusercontent.com/4274168/32667760-4e012fba-c644-11e7-8ca3-a0b18a739507.png)

**Comment by jeromecance** [comment]
Sadly, this is quite difficult for us to do that at the moment. Furthermore, we want to encourage people to write their playgrounds in English (bigger audience). In the future we'll probably focus more on teacher/student workflow (and so native language).
